name: Check coding style

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Flake8 dependencies
      run: python -m pip install -U flake8
    - name: Run Flake8
      run: flake8 .
    continue-on-error: true